# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.28.3/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.28.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/cyruspellet/Desktop/vrptk

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/cyruspellet/Desktop/vrptk

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.28.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.28.3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/cyruspellet/Desktop/vrptk/CMakeFiles /Users/cyruspellet/Desktop/vrptk//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/cyruspellet/Desktop/vrptk/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /Users/cyruspellet/Desktop/vrptk/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named vrptk

# Build rule for target.
vrptk: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vrptk
.PHONY : vrptk

# fast build rule for target.
vrptk/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vrptk.dir/build.make CMakeFiles/vrptk.dir/build
.PHONY : vrptk/fast

#=============================================================================
# Target rules for targets named glidescope

# Build rule for target.
glidescope: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glidescope
.PHONY : glidescope

# fast build rule for target.
glidescope/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glidescope.dir/build.make CMakeFiles/glidescope.dir/build
.PHONY : glidescope/fast

#=============================================================================
# Target rules for targets named vrptk_test

# Build rule for target.
vrptk_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vrptk_test
.PHONY : vrptk_test

# fast build rule for target.
vrptk_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vrptk_test.dir/build.make CMakeFiles/vrptk_test.dir/build
.PHONY : vrptk_test/fast

glidescope/engine.o: glidescope/engine.cpp.o
.PHONY : glidescope/engine.o

# target to build an object file
glidescope/engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glidescope.dir/build.make CMakeFiles/glidescope.dir/glidescope/engine.cpp.o
.PHONY : glidescope/engine.cpp.o

glidescope/engine.i: glidescope/engine.cpp.i
.PHONY : glidescope/engine.i

# target to preprocess a source file
glidescope/engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glidescope.dir/build.make CMakeFiles/glidescope.dir/glidescope/engine.cpp.i
.PHONY : glidescope/engine.cpp.i

glidescope/engine.s: glidescope/engine.cpp.s
.PHONY : glidescope/engine.s

# target to generate assembly for a file
glidescope/engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glidescope.dir/build.make CMakeFiles/glidescope.dir/glidescope/engine.cpp.s
.PHONY : glidescope/engine.cpp.s

glidescope/graphics.o: glidescope/graphics.cpp.o
.PHONY : glidescope/graphics.o

# target to build an object file
glidescope/graphics.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glidescope.dir/build.make CMakeFiles/glidescope.dir/glidescope/graphics.cpp.o
.PHONY : glidescope/graphics.cpp.o

glidescope/graphics.i: glidescope/graphics.cpp.i
.PHONY : glidescope/graphics.i

# target to preprocess a source file
glidescope/graphics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glidescope.dir/build.make CMakeFiles/glidescope.dir/glidescope/graphics.cpp.i
.PHONY : glidescope/graphics.cpp.i

glidescope/graphics.s: glidescope/graphics.cpp.s
.PHONY : glidescope/graphics.s

# target to generate assembly for a file
glidescope/graphics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glidescope.dir/build.make CMakeFiles/glidescope.dir/glidescope/graphics.cpp.s
.PHONY : glidescope/graphics.cpp.s

glidescope/main.o: glidescope/main.cpp.o
.PHONY : glidescope/main.o

# target to build an object file
glidescope/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glidescope.dir/build.make CMakeFiles/glidescope.dir/glidescope/main.cpp.o
.PHONY : glidescope/main.cpp.o

glidescope/main.i: glidescope/main.cpp.i
.PHONY : glidescope/main.i

# target to preprocess a source file
glidescope/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glidescope.dir/build.make CMakeFiles/glidescope.dir/glidescope/main.cpp.i
.PHONY : glidescope/main.cpp.i

glidescope/main.s: glidescope/main.cpp.s
.PHONY : glidescope/main.s

# target to generate assembly for a file
glidescope/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glidescope.dir/build.make CMakeFiles/glidescope.dir/glidescope/main.cpp.s
.PHONY : glidescope/main.cpp.s

glidescope/utils.o: glidescope/utils.cpp.o
.PHONY : glidescope/utils.o

# target to build an object file
glidescope/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glidescope.dir/build.make CMakeFiles/glidescope.dir/glidescope/utils.cpp.o
.PHONY : glidescope/utils.cpp.o

glidescope/utils.i: glidescope/utils.cpp.i
.PHONY : glidescope/utils.i

# target to preprocess a source file
glidescope/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glidescope.dir/build.make CMakeFiles/glidescope.dir/glidescope/utils.cpp.i
.PHONY : glidescope/utils.cpp.i

glidescope/utils.s: glidescope/utils.cpp.s
.PHONY : glidescope/utils.s

# target to generate assembly for a file
glidescope/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glidescope.dir/build.make CMakeFiles/glidescope.dir/glidescope/utils.cpp.s
.PHONY : glidescope/utils.cpp.s

glidescope/views/fleet.o: glidescope/views/fleet.cpp.o
.PHONY : glidescope/views/fleet.o

# target to build an object file
glidescope/views/fleet.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glidescope.dir/build.make CMakeFiles/glidescope.dir/glidescope/views/fleet.cpp.o
.PHONY : glidescope/views/fleet.cpp.o

glidescope/views/fleet.i: glidescope/views/fleet.cpp.i
.PHONY : glidescope/views/fleet.i

# target to preprocess a source file
glidescope/views/fleet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glidescope.dir/build.make CMakeFiles/glidescope.dir/glidescope/views/fleet.cpp.i
.PHONY : glidescope/views/fleet.cpp.i

glidescope/views/fleet.s: glidescope/views/fleet.cpp.s
.PHONY : glidescope/views/fleet.s

# target to generate assembly for a file
glidescope/views/fleet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glidescope.dir/build.make CMakeFiles/glidescope.dir/glidescope/views/fleet.cpp.s
.PHONY : glidescope/views/fleet.cpp.s

glidescope/views/inspector.o: glidescope/views/inspector.cpp.o
.PHONY : glidescope/views/inspector.o

# target to build an object file
glidescope/views/inspector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glidescope.dir/build.make CMakeFiles/glidescope.dir/glidescope/views/inspector.cpp.o
.PHONY : glidescope/views/inspector.cpp.o

glidescope/views/inspector.i: glidescope/views/inspector.cpp.i
.PHONY : glidescope/views/inspector.i

# target to preprocess a source file
glidescope/views/inspector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glidescope.dir/build.make CMakeFiles/glidescope.dir/glidescope/views/inspector.cpp.i
.PHONY : glidescope/views/inspector.cpp.i

glidescope/views/inspector.s: glidescope/views/inspector.cpp.s
.PHONY : glidescope/views/inspector.s

# target to generate assembly for a file
glidescope/views/inspector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glidescope.dir/build.make CMakeFiles/glidescope.dir/glidescope/views/inspector.cpp.s
.PHONY : glidescope/views/inspector.cpp.s

glidescope/views/nodes.o: glidescope/views/nodes.cpp.o
.PHONY : glidescope/views/nodes.o

# target to build an object file
glidescope/views/nodes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glidescope.dir/build.make CMakeFiles/glidescope.dir/glidescope/views/nodes.cpp.o
.PHONY : glidescope/views/nodes.cpp.o

glidescope/views/nodes.i: glidescope/views/nodes.cpp.i
.PHONY : glidescope/views/nodes.i

# target to preprocess a source file
glidescope/views/nodes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glidescope.dir/build.make CMakeFiles/glidescope.dir/glidescope/views/nodes.cpp.i
.PHONY : glidescope/views/nodes.cpp.i

glidescope/views/nodes.s: glidescope/views/nodes.cpp.s
.PHONY : glidescope/views/nodes.s

# target to generate assembly for a file
glidescope/views/nodes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glidescope.dir/build.make CMakeFiles/glidescope.dir/glidescope/views/nodes.cpp.s
.PHONY : glidescope/views/nodes.cpp.s

glidescope/views/schedule.o: glidescope/views/schedule.cpp.o
.PHONY : glidescope/views/schedule.o

# target to build an object file
glidescope/views/schedule.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glidescope.dir/build.make CMakeFiles/glidescope.dir/glidescope/views/schedule.cpp.o
.PHONY : glidescope/views/schedule.cpp.o

glidescope/views/schedule.i: glidescope/views/schedule.cpp.i
.PHONY : glidescope/views/schedule.i

# target to preprocess a source file
glidescope/views/schedule.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glidescope.dir/build.make CMakeFiles/glidescope.dir/glidescope/views/schedule.cpp.i
.PHONY : glidescope/views/schedule.cpp.i

glidescope/views/schedule.s: glidescope/views/schedule.cpp.s
.PHONY : glidescope/views/schedule.s

# target to generate assembly for a file
glidescope/views/schedule.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glidescope.dir/build.make CMakeFiles/glidescope.dir/glidescope/views/schedule.cpp.s
.PHONY : glidescope/views/schedule.cpp.s

glidescope/views/solution.o: glidescope/views/solution.cpp.o
.PHONY : glidescope/views/solution.o

# target to build an object file
glidescope/views/solution.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glidescope.dir/build.make CMakeFiles/glidescope.dir/glidescope/views/solution.cpp.o
.PHONY : glidescope/views/solution.cpp.o

glidescope/views/solution.i: glidescope/views/solution.cpp.i
.PHONY : glidescope/views/solution.i

# target to preprocess a source file
glidescope/views/solution.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glidescope.dir/build.make CMakeFiles/glidescope.dir/glidescope/views/solution.cpp.i
.PHONY : glidescope/views/solution.cpp.i

glidescope/views/solution.s: glidescope/views/solution.cpp.s
.PHONY : glidescope/views/solution.s

# target to generate assembly for a file
glidescope/views/solution.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glidescope.dir/build.make CMakeFiles/glidescope.dir/glidescope/views/solution.cpp.s
.PHONY : glidescope/views/solution.cpp.s

src/loaders/soln_loader.o: src/loaders/soln_loader.cpp.o
.PHONY : src/loaders/soln_loader.o

# target to build an object file
src/loaders/soln_loader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vrptk.dir/build.make CMakeFiles/vrptk.dir/src/loaders/soln_loader.cpp.o
.PHONY : src/loaders/soln_loader.cpp.o

src/loaders/soln_loader.i: src/loaders/soln_loader.cpp.i
.PHONY : src/loaders/soln_loader.i

# target to preprocess a source file
src/loaders/soln_loader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vrptk.dir/build.make CMakeFiles/vrptk.dir/src/loaders/soln_loader.cpp.i
.PHONY : src/loaders/soln_loader.cpp.i

src/loaders/soln_loader.s: src/loaders/soln_loader.cpp.s
.PHONY : src/loaders/soln_loader.s

# target to generate assembly for a file
src/loaders/soln_loader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vrptk.dir/build.make CMakeFiles/vrptk.dir/src/loaders/soln_loader.cpp.s
.PHONY : src/loaders/soln_loader.cpp.s

src/loaders/xml_loader.o: src/loaders/xml_loader.cpp.o
.PHONY : src/loaders/xml_loader.o

# target to build an object file
src/loaders/xml_loader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vrptk.dir/build.make CMakeFiles/vrptk.dir/src/loaders/xml_loader.cpp.o
.PHONY : src/loaders/xml_loader.cpp.o

src/loaders/xml_loader.i: src/loaders/xml_loader.cpp.i
.PHONY : src/loaders/xml_loader.i

# target to preprocess a source file
src/loaders/xml_loader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vrptk.dir/build.make CMakeFiles/vrptk.dir/src/loaders/xml_loader.cpp.i
.PHONY : src/loaders/xml_loader.cpp.i

src/loaders/xml_loader.s: src/loaders/xml_loader.cpp.s
.PHONY : src/loaders/xml_loader.s

# target to generate assembly for a file
src/loaders/xml_loader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vrptk.dir/build.make CMakeFiles/vrptk.dir/src/loaders/xml_loader.cpp.s
.PHONY : src/loaders/xml_loader.cpp.s

src/vrp.o: src/vrp.cpp.o
.PHONY : src/vrp.o

# target to build an object file
src/vrp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vrptk.dir/build.make CMakeFiles/vrptk.dir/src/vrp.cpp.o
.PHONY : src/vrp.cpp.o

src/vrp.i: src/vrp.cpp.i
.PHONY : src/vrp.i

# target to preprocess a source file
src/vrp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vrptk.dir/build.make CMakeFiles/vrptk.dir/src/vrp.cpp.i
.PHONY : src/vrp.cpp.i

src/vrp.s: src/vrp.cpp.s
.PHONY : src/vrp.s

# target to generate assembly for a file
src/vrp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vrptk.dir/build.make CMakeFiles/vrptk.dir/src/vrp.cpp.s
.PHONY : src/vrp.cpp.s

test/main.o: test/main.cpp.o
.PHONY : test/main.o

# target to build an object file
test/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vrptk_test.dir/build.make CMakeFiles/vrptk_test.dir/test/main.cpp.o
.PHONY : test/main.cpp.o

test/main.i: test/main.cpp.i
.PHONY : test/main.i

# target to preprocess a source file
test/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vrptk_test.dir/build.make CMakeFiles/vrptk_test.dir/test/main.cpp.i
.PHONY : test/main.cpp.i

test/main.s: test/main.cpp.s
.PHONY : test/main.s

# target to generate assembly for a file
test/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vrptk_test.dir/build.make CMakeFiles/vrptk_test.dir/test/main.cpp.s
.PHONY : test/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... glidescope"
	@echo "... vrptk"
	@echo "... vrptk_test"
	@echo "... glidescope/engine.o"
	@echo "... glidescope/engine.i"
	@echo "... glidescope/engine.s"
	@echo "... glidescope/graphics.o"
	@echo "... glidescope/graphics.i"
	@echo "... glidescope/graphics.s"
	@echo "... glidescope/main.o"
	@echo "... glidescope/main.i"
	@echo "... glidescope/main.s"
	@echo "... glidescope/utils.o"
	@echo "... glidescope/utils.i"
	@echo "... glidescope/utils.s"
	@echo "... glidescope/views/fleet.o"
	@echo "... glidescope/views/fleet.i"
	@echo "... glidescope/views/fleet.s"
	@echo "... glidescope/views/inspector.o"
	@echo "... glidescope/views/inspector.i"
	@echo "... glidescope/views/inspector.s"
	@echo "... glidescope/views/nodes.o"
	@echo "... glidescope/views/nodes.i"
	@echo "... glidescope/views/nodes.s"
	@echo "... glidescope/views/schedule.o"
	@echo "... glidescope/views/schedule.i"
	@echo "... glidescope/views/schedule.s"
	@echo "... glidescope/views/solution.o"
	@echo "... glidescope/views/solution.i"
	@echo "... glidescope/views/solution.s"
	@echo "... src/loaders/soln_loader.o"
	@echo "... src/loaders/soln_loader.i"
	@echo "... src/loaders/soln_loader.s"
	@echo "... src/loaders/xml_loader.o"
	@echo "... src/loaders/xml_loader.i"
	@echo "... src/loaders/xml_loader.s"
	@echo "... src/vrp.o"
	@echo "... src/vrp.i"
	@echo "... src/vrp.s"
	@echo "... test/main.o"
	@echo "... test/main.i"
	@echo "... test/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /Users/cyruspellet/Desktop/vrptk/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

